Initial abstraction
vostok/servicediscovery.telemetry.hercules pull request #1
Opened 2021-10-19 06:50 UTC by Jevvry

2021-10-20 13:36 UTC, TGladysheva commented on Vostok.ServiceDiscovery.Telemetry.Hercules/HerculesServiceDiscoveryEventBuilder.cs
> +﻿using System;
А где планируется использовать этот класс?

2021-10-28 17:06 UTC, TGladysheva commented on Vostok.ServiceDiscovery.Telemetry.Hercules/HerculesServiceDiscoveryEventBuilder.cs
> +namespace Vostok.ServiceDiscovery.Telemetry.Hercules
А для чего нам этот класс?

2021-10-28 17:07 UTC, TGladysheva commented on Vostok.ServiceDiscovery.Telemetry.Hercules/HerculesServiceDiscoveryEventBuilder.cs
> +namespace Vostok.ServiceDiscovery.Telemetry.Hercules
Точнее метод Build с такой сигнатурой

2021-10-30 17:05 UTC, Jevvry commented on Vostok.ServiceDiscovery.Telemetry.Hercules/HerculesServiceDiscoveryEventBuilder.cs
> +namespace Vostok.ServiceDiscovery.Telemetry.Hercules
Он используется в двух местах, [тут](https://github.com/vostok/servicediscovery.telemetry.hercules/blob/hercules_implementation/Vostok.ServiceDiscovery.Telemetry.Hercules/EventSender/HerculesServiceDiscoveryEventSender.cs#L21) и [тут](https://github.com/vostok/servicediscovery.telemetry.hercules/blob/hercules_implementation/Vostok.ServiceDiscovery.Telemetry.Hercules/HerculesServiceDiscoveryEventFactory.cs#L40).
Возможно, его стоит переместить в [HerculesServiceDiscoveryEventFactory](https://github.com/vostok/servicediscovery.telemetry.hercules/blob/hercules_implementation/Vostok.ServiceDiscovery.Telemetry.Hercules/HerculesServiceDiscoveryEventFactory.cs#L13) и сделать таки публичным

2021-12-07 10:34 UTC, KungA requested changes

2021-12-07 10:34 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry.Hercules/TagNames.cs
> +        public const string ServiceDiscoveryEventKind = "serviceDiscoveryEventKind";
просто kind будет норм

2021-12-07 10:34 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry.Hercules/HerculesServiceDiscoveryEventsFactory.cs
> +        public static HerculesEvent To([NotNull] ServiceDiscoveryEvent serviceDiscoveryEvent)
сомнительный метод, ещё и публичный

2021-12-07 10:34 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry.Hercules/EventSender/HerculesServiceDiscoveryEventsSenderSettings.cs
> +namespace Vostok.ServiceDiscovery.Telemetry.Hercules.EventSender
папка лишняя, можно вытащить

2021-12-07 10:34 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry.Hercules/EventReader/HerculesServiceDiscoveryEventsReader.cs
> +    public class HerculesServiceDiscoveryEventsReader
это что-то странное, должно было хватить максимально тупого преобразования HerculesEvent->ServiceDiscoveryEvent и использования hercules.consumers

2021-12-07 10:34 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry.Hercules/EventSender/HerculesServiceDiscoveryEventsSenderSettings.cs
> +        public string StreamName { get; set; } = "serviceDiscovery_event";
```suggestion
        public string StreamName { get; set; } = "serviceDiscovery_telemetry";
```

2021-12-07 10:34 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry.Hercules/EventSender/HerculesServiceDiscoveryEventsSenderSettings.cs
> +        public string StreamName { get; set; } = "serviceDiscovery_event";
у нас же будет ещё отдельный для клауда?

2021-12-07 10:34 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry.Hercules/EventSender/HerculesServiceDiscoveryEventsSenderSettings.cs
> +        public string StreamName { get; set; } = "serviceDiscovery_event";
возможно тогда и дефолт не нужен, и лучше обязательным сделать (как для логов)

2021-12-07 11:07 UTC, Jevvry commented on Vostok.ServiceDiscovery.Telemetry.Hercules/EventSender/HerculesServiceDiscoveryEventsSenderSettings.cs
> +        public string StreamName { get; set; } = "serviceDiscovery_event";
>  отдельный для клауда   

Да

2021-12-20 07:11 UTC, KungA approved these changes

2021-12-20 07:11 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry.Hercules/HerculesServiceDiscoveryEventsFactory.cs
> +        public static ServiceDiscoveryEvent From([NotNull] HerculesEvent herculesEvent)
глагол точно должен быть в названиях методов)

```suggestion
        public static ServiceDiscoveryEvent CreateFrom([NotNull] HerculesEvent herculesEvent)
```

2021-12-20 07:11 UTC, KungA commented on Vostok.ServiceDiscovery.Telemetry.Hercules/TagNames.cs
> +        public const string Kind = "serviceDiscoveryEventKind";
```suggestion
        public const string Kind = "kind";
```

не помню, но вроде уже оставлял такое

2021-12-20 08:08 UTC, merged